sudo: false
language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install coveralls pytest pytest-cov pycodestyle
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pycodestyle grift/
  - py.test --cov=grift grift/tests
after_success:
  - coveralls
